---
- name: Add user
  hosts: all
  tasks:
    - name: Add the user 'user_global' to deploy
      win_group_membership:
        name: deploy
        members:
          - user_global
        state: present

