---
- name: change permission
  hosts: all
  Tasks:
  - name: Remove FullControl AccessRule for User_cwk
    win_acl:
      path: c:\Temp\test.conf
      user: User_cwk
      rights: FullControl
      type: allow
      
