---
- name: change permission
  hosts: all
  Tasks:
  - name: Remove FullControl AccessRule for IIS_IUSRS
    win_acl:
      path: c:\Temp\test.conf
      user: User_cwk
      rights: FullControl
      type: allow
      state: absent
      inherit: ContainerInherit, ObjectInherit
      propagation: 'None'
