---
- name: change permission
  hosts: all
  tasks:
  - name: Add FullControl AccessRule for User_cwk
    win_acl:
      path: c:\Temp\test.conf
      user: user_cwk
      rights: FullControl
      type: allow
      
